standingssync/urls.py
from django.conf.urls import url
from . import views

app_name = "standingssync"

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^add_character/$", views.add_character, name="add_character"),
    url(
        r"^remove_character/(?P<alt_pk>[0-9]+)/$",
        views.remove_character,
        name="remove_character",
    ),
    url(
        r"^add_alliance_manager/$",
        views.add_alliance_manager,
        name="add_alliance_manager",
    ),
]

standingssync/models.py
import logging

from django.db import models
from django.utils.timezone import now

from allianceauth.authentication.models import CharacterOwnership
from allianceauth.eveonline.models import EveAllianceInfo, EveCharacter

from .managers import AllianceContactManager
from .utils import LoggerAddTag

logger = LoggerAddTag(logging.getLogger(__name__), __package__)


class SyncManager(models.Model):
    """An object for managing syncing of contacts for an alliance"""

    ERROR_NONE = 0
    ERROR_TOKEN_INVALID = 1
    ERROR_TOKEN_EXPIRED = 2
    ERROR_INSUFFICIENT_PERMISSIONS = 3
    ERROR_NO_CHARACTER = 4
    ERROR_ESI_UNAVAILABLE = 5
    ERROR_UNKNOWN = 99

    ERRORS_LIST = [
        (ERROR_NONE, "No error"),
        (ERROR_TOKEN_INVALID, "Invalid token"),
        (ERROR_TOKEN_EXPIRED, "Expired token"),
        (ERROR_INSUFFICIENT_PERMISSIONS, "Insufficient permissions"),
        (ERROR_NO_CHARACTER, "No character set for fetching alliance contacts"),
        (ERROR_ESI_UNAVAILABLE, "ESI API is currently unavailable"),
        (ERROR_UNKNOWN, "Unknown error"),
    ]

    alliance = models.OneToOneField(
        EveAllianceInfo, on_delete=models.CASCADE, primary_key=True
    )
    # alliance contacts are fetched from this character
    character = models.OneToOneField(
        CharacterOwnership, on_delete=models.SET_NULL, null=True, default=None
    )
    version_hash = models.CharField(max_length=32, null=True, default=None)
    last_sync = models.DateTimeField(null=True, default=None)
    last_error = models.IntegerField(choices=ERRORS_LIST, default=ERROR_NONE)

    def __str__(self):
        if self.character is not None:
            character_name = self.character.character.character_name
        else:
            character_name = "None"
        return "{} ({})".format(self.alliance.alliance_name, character_name)

    def set_sync_status(self, status):
        """sets the sync status with the current date and time"""
        self.last_error = status
        self.last_sync = now()
        self.save()

    def get_effective_standing(self, character: EveCharacter):
        """ return the effective standing with this alliance"""

        contacts = AllianceContact.objects.filter(manager=self).select_related()
        contact_found = None
        try:
            contact_found = contacts.get(contact_id=int(character.character_id))
        except AllianceContact.DoesNotExist:
            try:
                contact_found = contacts.get(contact_id=int(character.corporation_id))
            except AllianceContact.DoesNotExist:
                if character.alliance_id:
                    try:
                        contact_found = contacts.get(
                            contact_id=int(character.alliance_id)
                        )
                    except AllianceContact.DoesNotExist:
                        pass

        return contact_found.standing if contact_found else 0

    @classmethod
    def get_esi_scopes(cls) -> list:
        return ["esi-alliances.read_contacts.v1"]


class SyncedCharacter(models.Model):
    """A character that has his personal contacts synced with an alliance"""

    ERROR_NONE = 0
    ERROR_TOKEN_INVALID = 1
    ERROR_TOKEN_EXPIRED = 2
    ERROR_INSUFFICIENT_PERMISSIONS = 3
    ERROR_ESI_UNAVAILABLE = 5
    ERROR_UNKNOWN = 99

    ERRORS_LIST = [
        (ERROR_NONE, "No error"),
        (ERROR_TOKEN_INVALID, "Invalid token"),
        (ERROR_TOKEN_EXPIRED, "Expired token"),
        (ERROR_INSUFFICIENT_PERMISSIONS, "Insufficient permissions"),
        (ERROR_ESI_UNAVAILABLE, "ESI API is currently unavailable"),
        (ERROR_UNKNOWN, "Unknown error"),
    ]

    character = models.OneToOneField(
        CharacterOwnership, on_delete=models.CASCADE, primary_key=True
    )
    manager = models.ForeignKey(SyncManager, on_delete=models.CASCADE)
    version_hash = models.CharField(max_length=32, null=True, default=None)
    last_sync = models.DateTimeField(null=True, default=None)
    last_error = models.IntegerField(choices=ERRORS_LIST, default=ERROR_NONE)

    def __str__(self):
        return self.character.character.character_name

    def set_sync_status(self, status):
        """sets the sync status with the current date and time"""
        self.last_error = status
        self.last_sync = now()
        self.save()

    def get_status_message(self):
        if self.last_error != self.ERROR_NONE:
            message = self.get_last_error_display()
        elif self.last_sync is not None:
            message = "OK"
        else:
            message = "Not synced yet"

        return message

    @staticmethod
    def get_esi_scopes() -> list:
        return ["esi-characters.read_contacts.v1", "esi-characters.write_contacts.v1"]


class AllianceContact(models.Model):
    """An alliance contact with standing"""

    manager = models.ForeignKey(SyncManager, on_delete=models.CASCADE)
    contact_id = models.IntegerField()
    contact_type = models.CharField(max_length=32)
    standing = models.FloatField()

    objects = AllianceContactManager()

    def __str__(self):
        return "{}:{}".format(self.contact_type, self.contact_id)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["manager", "contact_id"], name="manager-contacts-unq"
            )
        ]

standingssync/templates/standingssync/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load static %}

{% block page_title %}{% trans app_title %}{% endblock %}
{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Sync of Alliance Standings" %}</h1>
        <div class="col-lg-10 col-lg-offset-1 container">            
            {% block details %}{% endblock %}
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link 
        href="{% static "standingssync/base.css" %}" 
        type="text/css" 
        rel="stylesheet"
    >
{% endblock %}

standingssync/templates/standingssync/index.html
{% extends 'standingssync/base.html' %}
{% load i18n %}
{% load humanize %}

{% block details %}    

    <div class="panel panel-primary">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% trans 'Alliance Available for Sync' %}</h3>
        </div>
        <div class="panel-body">            
            {% if alliance_contacts_count != None %}
                <img class="ra-avatar img-circle" src="{{ alliance.logo_url }}">
                &nbsp;&nbsp;
                {{ alliance.alliance_name }}
                &nbsp;                
                ({{ alliance_contacts_count }} contacts)
            {% else %}
                None
            {% endif %}
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% trans 'Your Synced Characters' %}</h3>
        </div>
        <div class="panel-body">            
            {% if has_synced_chars %}
                <table class="table" id="tab_standingssync">
                    <thead>                        
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Status</th>             
                            <th>Remove from Sync</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for character in characters %}
                            {% if character.has_error %}                                    
                                <tr class="danger">
                            {% else %}
                                <tr>    
                            {% endif %}                            
                                <td class="text-center"><img class="ra-avatar img-circle" src="{{ character.portrait_url }}">
                                </td>
                                <td>{{ character.name }}</td>
                                <td>{{ character.status_message }}</td>
                                <td><a class="btn btn-warning" href="{% url 'standingssync:remove_character' character.pk %}" role="button">
                                    <span class="fa fa-trash" style="font-size: 120%;"></span>
                                </a></td>
                            </tr>
                        {% endfor %}
                    </tbody>                        
                </table>
            {% else %}
                <p>None</p>
            {% endif %}
        </div>
    </div>

    {% if alliance_contacts_count == None and not perms.standingssync.add_syncmanager %}
        <div class="bs-callout bs-callout-warning">
        <h4>Warning</h4>        
            <p>
                {% if request.user.profile.main_character.alliance_name != None %}
                    This app is not fully setup yet for the 
                    <strong>{{ request.user.profile.main_character.alliance_name  }}</strong> alliance.
                {% else %}
                    You do not appear to belong to any alliance, but this app is for alliance members only.
                {% endif %}
                Please contact an admin for details.</p>
        </div>   
    {% endif %}

    {% if alliance_contacts_count != None %}            
        <a id="standingssyncBtnAddSyncChar" class="btn btn-primary" href="{% url 'standingssync:add_character' %}">Add Character to Sync</a>    
    {% endif %}
    
    {% if perms.standingssync.add_syncmanager %}        
        <a class="btn btn-default" href="{% url 'standingssync:add_alliance_manager' %}">            
            Set Alliance Character            
        </a>
    {% endif %}

    <div class="bs-callout bs-callout-warning">
        <h4>Read Me First</h4>
        <p>This app enables you to always have the current alliance standings on your non-alliance character. 
            Once activated it will automatically replace the personal contacts of your character with 
            the current Alliance contacts and will continue to do so until deactivated.</p>
            <p><strong>Careful!</strong> You will loose all your personal contacts on a synced character, so use with care.</p>
    </div>
        
{% endblock %}